<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <UserSecretsId>8feb569a-6e35-4e11-966f-1a9b12acc63e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="IGDB">
        <HintPath>..\..\..\..\.nuget\packages\igdb\6.1.0\lib\netstandard2.0\IGDB.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
