<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <UserSecretsId>0de09fbe-278b-4771-92c5-f795b6152bb4</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\GamesTimelineBlazor.Client\GamesTimelineBlazor.Client.csproj"/>
        <PackageReference Include="IGDB" Version="6.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12"/>
    </ItemGroup>

</Project>
